### ISSUE TITLE
无法使用啊

### ISSUE THREAD

**Issue by 1748582061** [iyzyi/naraka_bladepoint_pve#3]
开启之后前面都能动，但是到了这个界面之后就不动了，会是因为什么呢（试过列表里的所有脚本都是这个问题）
![Uploading 61b25175a9be0e8a7ecf1f8871d032d.png…]()

**Comment by iyzyi** [comment]
看不到图片

**Comment by 1748582061** [comment]
成功使用了，因为我下载错误，下载了运行的是源码而不是exe文件导致使用出错，十分感谢
